Stardog .NET example
Complexible/stardog-examples pull request #39
Opened 2020-01-30 15:31 UTC by joephayes

Stardog .NET example using the [TrinityRDF](https://trinity-rdf.net/) library.

- Updated README with data requirements and instructions on how to build and run .NET sample
- Added gradle build targets - `compileDotnet`and `runDotnet`

2020-01-30 19:25 UTC, snowell requested changes
Using a local checkout on my mac, `gradle compileDotnet` and `gradle runDotnet` are both failing:

```
✘ stephen:dotnet [ jph-dotnet-example | …3 ] ➭ gradle compileDotnet

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/stephen/stardog-examples/examples/dotnet/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating project ':examples:dotnet'.
> Could not get unknown property 'solution' for project ':examples:dotnet' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

2020-01-30 19:25 UTC, snowell commented on build.gradle
Gotta say that the indentation here bugs me a bit. Unless it's just Github's editor

2020-01-30 19:25 UTC, snowell commented on readme.md
> +gradle compileDotnet
Should we use gradle wrapper like we generally do, just to make sure differing gradle versions don't come back to bite us?

2020-01-30 19:25 UTC, snowell commented on examples/dotnet/README.md
> +* Stardog with a database named "music" populated the data from [music_schema.ttl](./examples/dotnet/TrinityConsoleSample/Ontologies/music_schema.ttl) and [music.ttl.gz](https://github.com/stardog-un
AFAICT this link is broken and possibly would be even after a merge

2020-01-30 19:25 UTC, snowell commented on examples/dotnet/README.md
> +* Stardog with a database named "music" populated the data from [music_schema.ttl](./examples/dotnet/TrinityConsoleSample/Ontologies/music_schema.ttl) and [music.ttl.gz](https://github.com/stardog-un
To clarify: the music_schema.ttl link

2020-01-30 20:17 UTC, joephayes commented on readme.md
> +gradle compileDotnet
my bad - tabs vs spaces. fixed.

2020-01-30 20:18 UTC, joephayes commented on build.gradle
my bad - tabs vs. spaces - fixed

2020-01-30 20:30 UTC, joephayes commented
@snowell RE: the build failure. please pull the latest - I had forgotten a properties file (hidden by gitignore) which defined the `solution` property.

2020-01-30 20:31 UTC, joephayes commented on readme.md
> +gradle compileDotnet
I was following what was already there - happy to switch it if that's the consensus.,

2020-01-30 21:34 UTC, joephayes commented on examples/dotnet/README.md
> +* Stardog with a database named "music" populated the data from [music_schema.ttl](./examples/dotnet/TrinityConsoleSample/Ontologies/music_schema.ttl) and [music.ttl.gz](https://github.com/stardog-un
removed the link

2020-01-31 12:34 UTC, snowell approved these changes

2020-02-03 16:57 UTC, merged