.NET sample updates
Complexible/stardog-examples pull request #42
Opened 2020-03-13 17:11 UTC by joephayes

No GitHub issue

Incorporate some suggestions from Sebastian at Semiodesk
Update to the latest Trinity RDF NuGet package (performance improvements and some bug fixes)

2020-03-17 18:47 UTC, joephayes commented
Bump @buzztroll @snowell @AlBaker

2020-03-17 19:49 UTC, snowell requested changes
Other than minor nitpicks, LGTM

2020-03-17 19:49 UTC, snowell commented on examples/dotnet/TrinityConsoleSample/Program.cs
> +            // 2. We do need a FROM to specify the named graph because it will be asserted by the Model
I assume this should be we "don't" need a FROM, seeing as this change got rid of it

2020-03-17 19:49 UTC, snowell commented on examples/dotnet/TrinityConsoleSample/Program.cs
> +                    Console.WriteLine($"\tMember: {binding.Values.First()}");
My C#-fu isn't what it used to be, but should there be a null check on Values?

2020-03-18 03:37 UTC, joephayes commented on examples/dotnet/TrinityConsoleSample/Program.cs
> +            // 2. We do need a FROM to specify the named graph because it will be asserted by the Model
whoops! fixed.

2020-03-18 03:41 UTC, joephayes commented on examples/dotnet/TrinityConsoleSample/Program.cs
> +                    Console.WriteLine($"\tMember: {binding.Values.First()}");
I changed it to `binding.Values.FirstOrDefault()?.ToString()` so if it is NULL it would print "NULL"

2020-03-18 11:23 UTC, snowell approved these changes

2020-03-18 15:15 UTC, merged