Fix typos and links
Complexible/stardog-examples pull request #44
Opened 2020-05-25 14:12 UTC by zacharywhitley

- Fixed typo
- Updated link to new archetype repo
- Fixed links that were returning 404
- Added links to existing examples

2020-05-28 16:43 UTC, igable requested changes
Looks good. Could you you squash these commit together?

2020-05-28 16:58 UTC, zacharywhitley commented
Sure can.

2020-05-28 18:42 UTC, zacharywhitley commented
Should be good now.

2020-05-28 21:19 UTC, igable commented on gradlew.bat
> +@if "%DEBUG%" == "" @echo off
Hmm. Prior to the squash there wasn't a change in this file. Is this all new line endings?

2020-05-29 00:40 UTC, zacharywhitley commented on gradlew.bat
> +@if "%DEBUG%" == "" @echo off
It’s just like ending changes. I’m not sure exactly what’s happening here but I have. Some ideas. My original edits were with the github web page. To squash I had to actually clone it. On checkout, without making any changes it lists those two files as having changes with the changes being line endings. I think it probably has to do with for and auto.crlf.  I believe it should now have windows line endings which I figured was ok since they’re .bat files and added that extension to the .gitattributes file.

2020-05-29 13:25 UTC, zacharywhitley commented
I see something got really messed up. I suspect there are problems with mixed line endings.

2020-05-29 13:25 UTC, closed without merging