Add instructions and YAML for Prometheus scraping
Complexible/stardog-examples pull request #50
Opened 2020-05-30 00:29 UTC by igable

Add an example Prometheus scrape job configuration and provide
instructions for configuring Prometheus to scrape stardog pods

2020-05-30 00:30 UTC, igable commented
I'm sure I'm going to find some typos on monday, but this is the general direction I'm headed.

2020-05-30 00:33 UTC, buzztroll requested changes

2020-05-30 00:33 UTC, buzztroll commented on examples/grafana/README.md
> +    stardog-admin user addrole --role monitoring monitor
is the role needed?

2020-05-30 00:33 UTC, buzztroll commented on examples/grafana/README.md
> +*screen shots go here*
should we get these in before merging?

2020-06-01 17:29 UTC, igable commented on examples/grafana/README.md
> +    stardog-admin user addrole --role monitoring monitor
discussed in slack. Dropping role creation.

2020-06-01 17:30 UTC, igable commented on examples/grafana/README.md
> +*screen shots go here*
We are merging to a feature branch and not develop so that Simon can add the screen shots.

2020-06-01 17:35 UTC, buzztroll commented on examples/grafana/README.md
> +*screen shots go here*
👍

2020-06-01 17:36 UTC, buzztroll approved these changes

2020-06-01 17:36 UTC, merged