Add an example of how to configure prometheus and grafana for stardog metrics
Complexible/stardog-examples pull request #51
Opened 2020-06-04 15:52 UTC by igable

2020-06-04 16:01 UTC, pdmars requested changes
Looks good. Few reword suggestions and spelling mistakes.

2020-06-04 16:01 UTC, pdmars commented on examples/grafana/README.md
> +configured to scrape Stardog kubenetes pods for metrics data.
s/kubenetes/kubernetes (k8s)

2020-06-04 16:01 UTC, pdmars commented on examples/grafana/README.md
> +with Prometheus you must create addition scrape jobs. When using Prometheus deployed with Helm the
additional

2020-06-04 16:01 UTC, pdmars commented on examples/grafana/README.md
> +simplest way is to pass in additional scaraping configs using a helm values file
s/scaraping/scraping

2020-06-04 16:01 UTC, pdmars commented on examples/grafana/README.md
> +The follow the [Grafana instructions](https://grafana.com/docs/grafana/latest/reference/export_import/#importing-a-dashboard)
s/The/Then

2020-06-04 16:01 UTC, pdmars commented on examples/grafana/README.md
> +able to read data but will be able to access the Prometheus monitoring endpoint:
suggestion, maybe reword: This user will be able to access the Prometheus endpoint.

2020-06-04 16:29 UTC, igable commented on examples/grafana/README.md
> +configured to scrape Stardog kubenetes pods for metrics data.
fixed

2020-06-04 16:30 UTC, igable commented on examples/grafana/README.md
> +with Prometheus you must create addition scrape jobs. When using Prometheus deployed with Helm the
fixed

2020-06-04 16:30 UTC, igable commented on examples/grafana/README.md
> +The follow the [Grafana instructions](https://grafana.com/docs/grafana/latest/reference/export_import/#importing-a-dashboard)
fixed

2020-06-04 16:30 UTC, igable commented on examples/grafana/README.md
> +able to read data but will be able to access the Prometheus monitoring endpoint:
done

2020-06-04 16:32 UTC, pdmars approved these changes
Looks great, thanks guys!

2020-06-09 06:59 UTC, buzztroll approved these changes

2020-10-16 19:18 UTC, merged